"use client"

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { motion } from "framer-motion"

const faqs = [
  {
    question: "Is this a loan? Do I need to pay anything back?",
    answer:
      "No, EduZero is not a loan service. You're simply using the rewards generated by your deposited money. Your deposit remains untouched, and there's nothing to pay back. It's a completely different model from traditional lending.",
  },
  {
    question: "What happens to my deposit? Can I withdraw it?",
    answer:
      "Your deposit is safely stored and represented as deposit tokens. You can withdraw your deposit after the minimum lock period of 30 days. Early withdrawals are subject to a 5% fee to ensure platform stability.",
  },
  {
    question: "How is the 5% annual reward rate guaranteed?",
    answer:
      "The 5% annual reward rate is fixed through a combination of financial strategies. The platform diversifies across multiple sources to ensure stability and consistency in returns, regardless of market conditions.",
  },
  {
    question: "What if I want to spend more than my available rewards?",
    answer:
      "You can only spend the rewards you've accumulated. If you need more spending power, you can either deposit more money or wait for more rewards to accumulate. We don't offer credit or advances on future rewards.",
  },
  {
    question: "Which merchants can I shop with?",
    answer:
      "We have partnerships with various merchants across categories like education, entertainment, shopping, and more. The list is constantly growing, and you can view all available merchants in the Shop section of your dashboard.",
  },
  {
    question: "Is my deposit insured or protected?",
    answer:
      "Your deposits are secured through multiple security measures. While not traditionally insured (as this is a new platform), we implement multiple security layers and regular audits to ensure the safety of user funds.",
  },
]

export function FAQ() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      viewport={{ once: true }}
      className="mb-12"
    >
      <h2 className="text-2xl font-bold mb-6 text-center">Frequently Asked Questions</h2>
      <Accordion type="single" collapsible className="max-w-3xl mx-auto">
        {faqs.map((faq, index) => (
          <AccordionItem key={index} value={`item-${index}`}>
            <AccordionTrigger>{faq.question}</AccordionTrigger>
            <AccordionContent>{faq.answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>
    </motion.div>
  )
}
